services:
  backend:
    build:
      context: backend/
    environment:
      CORS_ORIGIN: "http://localhost"
    ports:
      - 8080:8080
  frontend:
    build:
      context: frontend/
    ports:
      - 80:80
    depends_on:
      - backend
